version: '3.8'

services:
  client:
    build: 
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:5000
      - REACT_APP_ML_API_URL=http://localhost:6000
      - NODE_ENV=development
      - REACT_APP_GOOGLE_CLIENT_ID=64073786957-6vdvf5mt3ps1gthf0jgpdd17tb9i7rla.apps.googleusercontent.com
    depends_on:
      - server
    networks:
      - app-network

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
      - /app/node_modules
    environment:
      - DOCKER_ENV=true
      - JWT_SECRET=your_jwt_secret
      - ML_API_URL=http://ml-api:6000
      - MONGODB_URI=mongodb://mongodb:27017/capstone-project
      - GOOGLE_CLIENT_ID=your_google_client_id_here
    depends_on:
      mongodb:
        condition: service_started
    networks:
      - app-network

  ml-api:
    build:
      context: ./ml-api
      dockerfile: Dockerfile
    ports:
      - "6000:6000"
    volumes:
      - ./ml-api:/app
    environment:
      - MODEL_PATH=/app/models/sentiment_model.pkl
    networks:
      - app-network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data: 