name: Sonar Scan

on:
  workflow_dispatch:
    inputs:
      projectKey:
        required: true
      organization:
        required: true

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Sonar Scan
        uses: SonarSource/sonarqube-scan-action@v2
        with:
          args: >
            -Dsonar.projectKey=${{ inputs.projectKey }}
            -Dsonar.organization=${{ inputs.organization }}
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
